version: '3.8'

services:

  db:
    image: postgres:13
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: scala-app
    ports:
      - 9000:9000
    depends_on:
      - db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - DATABASE_URL=${POSTGRES_USER}://${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    command: sbt run 